version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"       # Serve static HTML through port 8080 → container port 80 (Nginx)
    depends_on:
      - backend
